stages:
  - build
  - package
  - upload
  - release

.only-default: &only-default
  only:
    - master
    - merge_requests
    - tags

compile:
  only:
    - branches
    - merge_requests
    - tags
  stage: build
  image: golang:1.16
  script:
    - make build-cli
  artifacts:
    paths:
      - build/

package:
  <<: *only-default
  stage: package
  needs:
    - job: compile
      artifacts: true
  tags:
    - bigbang
    - packages
  image: golang:1.16
  before_script:
    - ./build/zarf tools registry login registry1.dso.mil --username "$REGISTRY1_USERNAME_ZARF_ROBOT" --password "$REGISTRY1_PASSWORD_ZARF_ROBOT"
  script:
    - make ci-release
  after_script:
    - echo "PACKAGE_JOB_ID=$CI_JOB_ID" >> job.env
  artifacts:
    reports:
      dotenv: job.env
    paths:
      - build/

artifact-upload:
  image: amazon/aws-cli
  stage: upload
  needs:
    - job: package
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - aws s3 cp build s3://zarf-public/release/$CI_COMMIT_TAG --region us-gov-west-1 --recursive

generate-release:
  image: registry.gitlab.com/gitlab-org/release-cli:v0.8.0
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  needs:
    - job: artifact-upload
  script:
    - release-cli create --name "Zarf ${CI_COMMIT_TAG}" --tag-name "${CI_COMMIT_TAG}" --description "Zarf K8s Airgap Buddy"
      --assets-link "{\"name\":\"zarf\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf\"}"
      --assets-link "{\"name\":\"zarf-mac-apple\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-mac-apple\"}"
      --assets-link "{\"name\":\"zarf-mac-intel\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-mac-intel\"}"
      --assets-link "{\"name\":\"zarf-init-amd64.tar.zst\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-init-amd64.tar.zst\"}"
      --assets-link "{\"name\":\"zarf-init-arm64.tar.zst\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf-init-arm64.tar.zst\"}"
      --assets-link "{\"name\":\"zarf.sha256\",\"url\":\"https://zarf-public.s3-us-gov-west-1.amazonaws.com/release/$CI_COMMIT_TAG/zarf.sha256\"}"
