repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
        exclude: "src/test/e2e/29_config_file_test.go"
      - id: end-of-file-fixer
        exclude: site/src/content/docs/commands/.*
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
        exclude: site/src/content/docs/commands/.*
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.4
    hooks:
      - id: fix-smartquotes
  - repo: local
    hooks:
      - id: check-docs-and-schema
        name: Check for outdated docs and Zarf schema
        entry: ./hack/check-zarf-docs-and-schema.sh
        files: "src/types/types.go"
        types: [go]
        language: script
      - id: goimports
        name: goimports
        entry: golangci-lint run --enable-only goimports --fix
        types: [go]
        language: golang
        pass_filenames: false
      - id: lint
        name: golangci-lint go lint
        entry: golangci-lint run
        types: [go]
        language: golang
        pass_filenames: false
