repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
        exclude: |
          (?x)^(
            examples/big-bang/kustomizations/bigbang/values.yaml|
            examples/software-factory/template/bigbang/values.yaml|
            examples/istio-with-separate-cert/files/bigbangdev.key
          )$
      - id: end-of-file-fixer
        exclude: "^examples/big-bang/template/bigbang/vendor/.*$"
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        exclude: "^examples/big-bang/template/bigbang/vendor/.*$"
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.4.0
    hooks:
      - id: go-fmt
      - id: golangci-lint
  - repo: local
    hooks:
      - id: generate-zarf-schema
        name: Check for outdated Zarf schema
        entry: hooks/verify-zarf-schema.sh
        files: "cli/types/types.go"
        types: [go]
        language: script
        description: "Runs `zarf tools config-schema > zarf.schema.json` to ensure schema is up to date"
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.14.0
    hooks:
      - id: check-jsonschema
        name: "Validate Zarf Configs Against Schema"
        files: "zarf.yaml"
        types: [yaml]
        args: ["--schemafile", "zarf.schema.json"]
