repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: check-merge-conflict
      - id: detect-aws-credentials
        args:
          - "--allow-missing-credentials"
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/sirosen/texthooks
    rev: 0.6.4
    hooks:
      - id: fix-smartquotes
  - repo: local
    hooks:
      - id: check-docs-and-schema
        name: Check for outdated docs and Zarf schema
        entry: ./hack/check-zarf-docs-and-schema.sh
        files: "src/types/types.go"
        types: [go]
        language: script
      - id: goimports
        name: goimports
        entry: goimports
        files: .go$
        args:
          - -l
          - -w
        language: system
        pass_filenames: true
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.14.0
    hooks:
      - id: check-jsonschema
        name: "Validate Zarf Configs Against Schema"
        files: "zarf.yaml"
        types: [yaml]
        args: ["--schemafile", "zarf.schema.json"]
        exclude: |
          (?x)^(
            src/test/packages/12-lint/.*
          )$
