redis-ha:
  enabled: false

dex:
  enabled: false

notifications:
  enabled: false

configs:
  repositories:
    github-podinfo:
      name: podinfo
      url: https://github.com/stefanprodan/podinfo.git
      username: ""
      password: ""
    argocd-example-apps:
      name: argocd-example-apps
      url: https://github.com/argoproj/argocd-example-apps.git
      username: ""
      password: ""

redis:
  image:
    repository: docker.io/library/redis
