replicaCount: 1

podLabels: {}

image:
  repository: registry
  tag: 2.8.3

proxy:
  enabled: false
  injectorHostPort: 5001
  image:
    repository: alpine/socat
    tag: 1.8.0.3
  injector:
    image: registry.k8s.io/pause:3.10
    payLoadConfigMapAmount: 0
    shasum: ""

ipv6Only: false

service:
  name: registry
  type: NodePort
  port: 5000

resources: {}

persistence:
  accessMode: "ReadWriteOnce"
  enabled: true
  size: 20Gi
  deleteEnabled: true

secrets:
  htpasswd: ""
  configData:
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
    http:
      secret: ""
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
      tls:
        certificate: /certs/server/tls.crt
        key: /certs/server/tls.key
        clientcas:
          - /certs/ca/ca.pem
        clientauth: require-and-verify-client-cert
        minimumtls: tls1.2
      debug:
        addr: :5001
        prometheus:
          enabled: false
          path: /metrics
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3

podDisruptionBudget:
  minAvailable: 1

affinity:
  enabled: true
  custom: {}

tolerations: []

autoscaling:
  enabled: true
  mapReplicasToNodes: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80

caBundle: ""
## One or more concatenated certificates
## Will be mounted to /etc/ssl/certs/ca-certificates.crt
# caBundle: |
#   # Root CA 1
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
#   # Intermediate CA 1
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----
#   # Root CA 2
#   -----BEGIN CERTIFICATE-----
#   ...
#   -----END CERTIFICATE-----

extraEnvVars: []
## Additional ENV variables to set
# - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
#   value: "/var/lib/example"

serviceAccount:
  create: false
  name: ""
  annotations: {}
