apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      version: '6.4.0'
      sourceRef:
        kind: HelmRepository
        name: podinfo
      interval: 5m0s
  targetNamespace: podinfo-helm
