applications:
  - name: apps
    namespace: argocd
    finalizers:
      - resources-finalizer.argocd.argoproj.io
    project: default
    sources:
      - repoURL: https://github.com/stefanprodan/podinfo.git
        path: ./charts/podinfo
        targetRevision: 6.4.0
        helm:
          valueFiles:
            - values.yaml
    syncPolicy:
      automated: { }
    destination:
      namespace: default
      server: https://kubernetes.default.svc
