[package.create]
flavor = "registry1.alpha"
architecture = "amd64"

[package.create.set]
# The image reference to use for the Zarf agent, defaults to a locally built image
agent_image_domain = "registry1.dso.mil/"
agent_image = "ironbank/opensource/defenseunicorns/zarf/zarf-agent"
# renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/defenseunicorns/zarf/zarf-agent
agent_image_tag = "v0.32.6"

# Tag for the zarf injector binary to use
injector_version = "2023-08-02"
injector_amd64_shasum = "91de0768855ee2606a4f85a92bb480ff3a14ca205fd8d05eb397c18e15aa0247"
injector_arm64_shasum = "663df681deea957b0ec53538eab221691a83de8e95d86b8a29008af711934bee"

# The image reference to use for the registry that Zarf deploys into the cluster
registry_image_domain = ""
registry_image = "library/registry"
# change this to use registry1 image when the image is available there - need alpha image for IRSA s3 backend access
# renovate: datasource=docker depName=docker.io/library/registry versioning=loose
registry_image_tag = "3.0.0-alpha.1"

# The image reference to use for the optional git-server Zarf deploys
# renovate: datasource=docker depName=registry1.dso.mil/ironbank/opensource/go-gitea/gitea
gitea_image = "registry1.dso.mil/ironbank/opensource/go-gitea/gitea:v1.21.5"
