apiVersion: v1
kind: Service
metadata:
  name: agent-redirector
  namespace: zarf
  # labels:
  #   zarf.dev/connect-name: agent-redirector
spec:
  selector:
    app: agent-redirector
  ports:
    - port: 443
      targetPort: 8444
