domain: bigbang.dev

registryCredentials:
  registry: "###ZARF_REGISTRY###"
  username: "zarf-pull"
  password: "###ZARF_REGISTRY_AUTH_PULL###"

git:
  existingSecret: "zarf-git-secret"

networkPolicies:
  enabled: true
  # When in prod use a real CIDR. Don't do this, it isn't secure. This is done here since it is a demo and the CIDR changes based on which Linux distro you are running on.
  controlPlaneCidr: "0.0.0.0/0"
  nodeCidr: "0.0.0.0/0"
  vpcCidr: "0.0.0.0/0"

istio:
  enabled: true
  ingressGateways:
    public-ingressgateway:
      type: "LoadBalancer"
      kubernetesResourceSpec:
        resources:
          requests:
            cpu: "50m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
  gateways:
    public:
      tls:
        key: |
          -----BEGIN PRIVATE KEY-----
          MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDTogvrzocgDZcc
          +F2+e4Vk46tuGr2tyAlVdMOiF2iRxhME5AIrPZaRURA2CudHXCpRpQvOkqMN8epN
          cYKgaZltjBz8vGeCyTI4266jEICBrAMaFvpm7RVDjn6yywMhQS1aIeHUlPGYqOJO
          iiA/h/QNdskupUdLk0rdmqUmaZM8JBS2nauFtqo0hEHx2qaCnmqgbSjH4JcHRAZy
          siz78OTO+8zC5ZoeMs5NrF8QvydSKtmEqJkVcgovDWGQsiMtqi46HngCMRw24jB5
          dKo3lSNlLmoBtC5X2gt528hgzy8fCseVGry3WGbTtR5qKHKI0cyPPBI1++UwyP8X
          dObst2MjAgMBAAECggEADrz2P5G+b0kDAQ162c0YWRJR2fUayINpwv3CsgMXUS+O
          G4UVcZV0auJOUrUnrhyJBe6Mh/JGUK5MNuB0zF8OREbBrggg3UbNrI//9XMsv9sO
          zD5Vad2Q4YeG40SoDyTO17wMUhWdTZhVSkrsPABnypg/InR4Jpc3W39tiONJUaLB
          LhgICRAk5MdvLYsGkjebOPKGx2sy4oHvTZ4HRr9z0h+jGIUpFhTc/ED/A+JoMg0f
          pQEpgJahj5r1Gn8morAN8XJdeNQkpC75o8yFgdy3awYBuf9ZqhURhircMaxr3INs
          cdpMtdEAy0wKexqEzQPuLrH9hX1y/8iXVe8SggcqwQKBgQDw/7u12dk1gFnueAO5
          hEii3HaT6GsYaB7VH03mnTy050u0ZgtzxVZmPHN8cKgqT2HgKz83f+RfQEx1PC87
          H96hFA/2dcufrP0BFU3k68kvnwM5KAWHfzJ1PmTQaIZ+h4Yo9isJ8wuoqPW8pqSP
          CREJeSb07ZtcTCPs1fbC5Z9f2QKBgQDgzl98AR0Qz0uI0eQoJ/Hben91k7y2nfo8
          yyCw5kqXeRtF5l+OfqtSsKJgqzpu9l76k3oRY0nJ/m4Xxnlrbawa3OWCCtjzqG4r
          a+IKtySBI2ypyFiDw9wcOIbEHJizrjgOu0bVFoukkpTgk+TRzOS0lGParPM94t90
          nDmvS+E5WwKBgEE2kk7FIlet4af75dYfi6A2VAf2DnTOR/mXvPa4eaLiK8QnENZF
          AfosRXvY6Eh6rpuAWFzmSJ/VwFrA7G7tUsr3qNIiUfVlVBkk8K0PeKNgPfkLcWOW
          8cp0FcenYS1/8rfG1SKeF/uNrOFdno3uACQ2GmqQmUfCer4tr9ZRWG0RAoGBANuB
          p0p16+OWBbM6/wUWu9oK6pnr/8Bw0P67eNhChWMSJcdDAtsoZDEBuAucJhpjBqq1
          heOkh1Bs1yLv8W8sT3iLaK5p2R1RwQE0/ipoWYSfCmNd9M/0VuBXcX/cTF5mJuZ7
          htZahU/UsPn4bt1Mq6SHoFjNt1UeSgKa6Nh5xxkxAoGAX6uh2vUleUPeKNhYQigB
          l9zlDpbtCpwfMds189HQufpVUsunP4183pE3PuGcO5NcUPsnFPJx/9CLbDeznAUT
          ZSiedu5LBQD9enuns5qja1JCLTczx4h9J4VC5dta2LwJEKdl3JFV0TtRLZem4vkw
          PMvLLr/bq/3meBHUPHFCbVI=
          -----END PRIVATE KEY-----
        cert: |
          -----BEGIN CERTIFICATE-----
          MIIFHzCCBAegAwIBAgISBJmTT+NKxDDIk28TBZXhUpGNMA0GCSqGSIb3DQEBCwUA
          MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
          EwJSMzAeFw0yMjAzMTUwODE1MDhaFw0yMjA2MTMwODE1MDdaMBgxFjAUBgNVBAMM
          DSouYmlnYmFuZy5kZXYwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDT
          ogvrzocgDZcc+F2+e4Vk46tuGr2tyAlVdMOiF2iRxhME5AIrPZaRURA2CudHXCpR
          pQvOkqMN8epNcYKgaZltjBz8vGeCyTI4266jEICBrAMaFvpm7RVDjn6yywMhQS1a
          IeHUlPGYqOJOiiA/h/QNdskupUdLk0rdmqUmaZM8JBS2nauFtqo0hEHx2qaCnmqg
          bSjH4JcHRAZysiz78OTO+8zC5ZoeMs5NrF8QvydSKtmEqJkVcgovDWGQsiMtqi46
          HngCMRw24jB5dKo3lSNlLmoBtC5X2gt528hgzy8fCseVGry3WGbTtR5qKHKI0cyP
          PBI1++UwyP8XdObst2MjAgMBAAGjggJHMIICQzAOBgNVHQ8BAf8EBAMCBaAwHQYD
          VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
          BBYEFN/T49HKcfymGwkOFTz8OtpDJucYMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJ
          QOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3Iz
          Lm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcv
          MBgGA1UdEQQRMA+CDSouYmlnYmFuZy5kZXYwTAYDVR0gBEUwQzAIBgZngQwBAgEw
          NwYLKwYBBAGC3xMBAQEwKDAmBggrBgEFBQcCARYaaHR0cDovL2Nwcy5sZXRzZW5j
          cnlwdC5vcmcwggEDBgorBgEEAdZ5AgQCBIH0BIHxAO8AdQApeb7wnjk5IfBWc59j
          pXflvld9nGAK+PlNXSZcJV3HhAAAAX+M3BZDAAAEAwBGMEQCIAsLQZOU6ueANq2a
          niam7DByhSTeKIpA04WtNSyQaoEFAiAnJGI1Qq7UVL2ziBJeSmqTXNmVr8btxNc7
          T0MGQdJPyAB2AG9Tdqwx8DEZ2JkApFEV/3cVHBHZAsEAKQaNsgiaN9kTAAABf4zc
          F38AAAQDAEcwRQIgYO4X4fqQ8FXKsaz2epETaqeyaU8GGvN9lalfCSZf52ACIQDl
          u0lDRylGA4pZdFFBHQ66stYfxYPRflXZEFgyqvkEdDANBgkqhkiG9w0BAQsFAAOC
          AQEAoliSWhVEs8W2VBCR5dLB8v82tRC8xDuYEMVUlcQBe5uMA+8iHYJb9z+Af6IB
          59LF30e1qfZ8Mo8uBajxMlm7aH6065sTRIfIYrrikPYdSBP+KkE8KXdHygjWjvnd
          eIQKP99HCQTy+WIFddNAp6c3cJUCMEdmbLVbM+cqK9XTAeCWfH54IrCOTK1FJluu
          sAKAJtcaL3oqAaFDnrZRJ7E4d5XltDDhPRJ/Hh4wu0YfOdRdFuAo6noHtvy5M/So
          hgGZkBFqgoXhLqNxT2RHqGuK1MxPRQSZQ82/PkClu+XtMYDbRDCZWY1up8pCtyvg
          YMtfEJbrfBOmH+uA6dgwhJ8sBw==
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
          WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
          RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
          AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
          R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
          sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
          NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
          Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
          /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
          AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
          Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
          FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
          AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
          Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
          gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
          PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
          ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
          CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
          lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
          avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
          yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
          yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
          hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
          HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
          MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
          nLRbwHOoq7hHwg==
          -----END CERTIFICATE-----
          -----BEGIN CERTIFICATE-----
          MIIFYDCCBEigAwIBAgIQQAF3ITfU6UK47naqPGQKtzANBgkqhkiG9w0BAQsFADA/
          MSQwIgYDVQQKExtEaWdpdGFsIFNpZ25hdHVyZSBUcnVzdCBDby4xFzAVBgNVBAMT
          DkRTVCBSb290IENBIFgzMB4XDTIxMDEyMDE5MTQwM1oXDTI0MDkzMDE4MTQwM1ow
          TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
          cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwggIiMA0GCSqGSIb3DQEB
          AQUAA4ICDwAwggIKAoICAQCt6CRz9BQ385ueK1coHIe+3LffOJCMbjzmV6B493XC
          ov71am72AE8o295ohmxEk7axY/0UEmu/H9LqMZshftEzPLpI9d1537O4/xLxIZpL
          wYqGcWlKZmZsj348cL+tKSIG8+TA5oCu4kuPt5l+lAOf00eXfJlII1PoOK5PCm+D
          LtFJV4yAdLbaL9A4jXsDcCEbdfIwPPqPrt3aY6vrFk/CjhFLfs8L6P+1dy70sntK
          4EwSJQxwjQMpoOFTJOwT2e4ZvxCzSow/iaNhUd6shweU9GNx7C7ib1uYgeGJXDR5
          bHbvO5BieebbpJovJsXQEOEO3tkQjhb7t/eo98flAgeYjzYIlefiN5YNNnWe+w5y
          sR2bvAP5SQXYgd0FtCrWQemsAXaVCg/Y39W9Eh81LygXbNKYwagJZHduRze6zqxZ
          Xmidf3LWicUGQSk+WT7dJvUkyRGnWqNMQB9GoZm1pzpRboY7nn1ypxIFeFntPlF4
          FQsDj43QLwWyPntKHEtzBRL8xurgUBN8Q5N0s8p0544fAQjQMNRbcTa0B7rBMDBc
          SLeCO5imfWCKoqMpgsy6vYMEG6KDA0Gh1gXxG8K28Kh8hjtGqEgqiNx2mna/H2ql
          PRmP6zjzZN7IKw0KKP/32+IVQtQi0Cdd4Xn+GOdwiK1O5tmLOsbdJ1Fu/7xk9TND
          TwIDAQABo4IBRjCCAUIwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8EBAMCAQYw
          SwYIKwYBBQUHAQEEPzA9MDsGCCsGAQUFBzAChi9odHRwOi8vYXBwcy5pZGVudHJ1
          c3QuY29tL3Jvb3RzL2RzdHJvb3RjYXgzLnA3YzAfBgNVHSMEGDAWgBTEp7Gkeyxx
          +tvhS5B1/8QVYIWJEDBUBgNVHSAETTBLMAgGBmeBDAECATA/BgsrBgEEAYLfEwEB
          ATAwMC4GCCsGAQUFBwIBFiJodHRwOi8vY3BzLnJvb3QteDEubGV0c2VuY3J5cHQu
          b3JnMDwGA1UdHwQ1MDMwMaAvoC2GK2h0dHA6Ly9jcmwuaWRlbnRydXN0LmNvbS9E
          U1RST09UQ0FYM0NSTC5jcmwwHQYDVR0OBBYEFHm0WeZ7tuXkAXOACIjIGlj26Ztu
          MA0GCSqGSIb3DQEBCwUAA4IBAQAKcwBslm7/DlLQrt2M51oGrS+o44+/yQoDFVDC
          5WxCu2+b9LRPwkSICHXM6webFGJueN7sJ7o5XPWioW5WlHAQU7G75K/QosMrAdSW
          9MUgNTP52GE24HGNtLi1qoJFlcDyqSMo59ahy2cI2qBDLKobkx/J3vWraV0T9VuG
          WCLKTVXkcGdtwlfFRjlBz4pYg1htmf5X6DYO8A4jqv2Il9DjXA6USbW1FzXSLr9O
          he8Y4IWS6wY7bCkjCWDcRQJMEhg76fsO3txE+FiYruq9RUWhiF1myv4Q6W+CyBFC
          Dfvp7OOGAN6dEOM4+qR9sdjoSYKEBpsr6GtPAQw4dy753ec5
          -----END CERTIFICATE-----
  values:
    hub: "###ZARF_REGISTRY###/ironbank/opensource/istio"
    istiod:
      resources:
        requests:
          cpu: "50m"
          memory: "512Mi"
        limits:
          cpu: "500m"
          memory: "1Gi"
      hpaSpec:
        maxReplicas: 1
   
istiooperator:
  enabled: true
  git:
    repo: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__core__istio-operator.git
  values:
    hub: "###ZARF_REGISTRY###/ironbank/opensource/istio"
    operator:
      resources:
        limits:
          cpu: "200m"
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "128Mi"

jaeger:
  enabled: true
  values:
    jaeger:
      spec:
        allInOne:
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
        collector:
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "50m"
        memory: "64Mi"

kiali:
  enabled: true
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "256Mi"
      limits:
        cpu: "100m"
        memory: "512Mi"
    cr:
      spec:
        deployment:
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "368Mi"
    svcPatchJob:
      image:
        repository: "###ZARF_REGISTRY###/ironbank/big-bang/base"

clusterAuditor:
  enabled: true
  values:
    resources:
      requests:
        cpu: "50m"
        memory: "150Mi"
      limits:
        cpu: "300m"
        memory: "300Mi"

gatekeeper:
  enabled: true
  values:
    controllerManager:
      resources:
        limits:
          cpu: "175m"
          memory: "512Mi"
        requests:
          cpu: "50m"
          memory: "256Mi"
    audit:
      resources:
        limits:
          cpu: "500m"
          memory: "768Mi"
        requests:
          cpu: "50m"
          memory: "256Mi"
    violations:
      allowedDockerRegistries:
        parameters:
          repos:
            - "###ZARF_REGISTRY###"
          excludedResources:
            # K3s kube-system stuff, better than excluding the whole namespace
            - "kube-system/coredns-.*"
            - "kube-system/local-path-provisioner-.*"
            - "kube-system/metrics-server-.*"
            - "kube-system/svclb-.*"
            - "kube-system/traefik-.*"
            # K3s needs these due to how it creates services of type "LoadBalancer"
            - "istio-system/lb-port-.*"
            - "istio-system/svclb-.*"
            # K3s needs this if you are doing K3s-specific "HelmRelease"-type CRDs
            - ".*/helm-install-.*"
            - ".*/helm"
            # TODO: Get Zarf images in Iron Bank and don't wildcard the whole namespace
            - "zarf/.*"
      hostNetworking:
        parameters:
          excludedResources:
            # K3s needs these due to how it creates services of type "LoadBalancer"
            - "istio-system/svclb-.*"
            - "istio-system/lb-port-.*"

logging:
  enabled: true
  values:
    kibana:
      count: 1
      resources:
        requests:
          memory: "512Mi"
          cpu: "50m"
        limits:
          memory: "1Gi"
          cpu: "500m"
    elasticsearch:
      master:
        count: 1
        resources:
          limits:
            cpu: "500m"
            memory: "3Gi"
          requests:
            cpu: "50m"
            memory: "1Gi"
      data:
        count: 1
        resources:
          limits:
            cpu: "500m"
            memory: "3Gi"
          requests:
            cpu: "50m"
            memory: "1Gi"

eckoperator:
  enabled: true
  values:
    resources:
      limits:
        cpu: "200m"
        memory: "256Mi"
      requests:
        cpu: "50m"
        memory: "128Mi"

fluentbit:
  enabled: true
  values:
    resources:
      limits:
        cpu: "100m"
        memory: "128Mi"
      requests:
        cpu: "50m"
        memory: "64Mi"

monitoring:
  enabled: true
  values:
    cleanUpgrade:
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "100m"
    alertmanager:
      alertmanagerSpec:
        image:
          repository: "###ZARF_REGISTRY###/ironbank/opensource/prometheus/alertmanager"
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "50Mi"
    grafana:
      image:
        repository: "###ZARF_REGISTRY###/ironbank/opensource/grafana/grafana"
      resources:
        limits:
          cpu: "100m"
          memory: "256Mi"
        requests:
          cpu: "50m"
          memory: "128Mi"
      testFramework:
        image: "###ZARF_REGISTRY###/ironbank/opensource/bats/bats"
      sidecar:
        image:
          repository: "###ZARF_REGISTRY###/ironbank/kiwigrid/k8s-sidecar"
        resources:
          limits:
            cpu: "100m"
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "50Mi"
      downloadDashboardsImage:
        repository: "###ZARF_REGISTRY###/ironbank/big-bang/base"
      downloadDashboards:
        resources:
          limits:
            cpu: "20m"
            memory: "20Mi"
          requests:
            cpu: "20m"
            memory: "20Mi"
    kube-state-metrics:
      image:
        repository: "###ZARF_REGISTRY###/ironbank/opensource/kubernetes/kube-state-metrics"
      resources:
        limits:
          cpu: "100m"
          memory: "128Mi"
        requests:
          cpu: "50m"
          memory: "64Mi"
    prometheus-node-exporter:
      image:
        repository: "###ZARF_REGISTRY###/ironbank/opensource/prometheus/node-exporter"
      resources:
        limits:
          cpu: "200m"
          memory: "50Mi"
        requests:
          cpu: "50m"
          memory: "50Mi"
    prometheusOperator:
      admissionWebhooks:
        patch:
          image:
            repository: "###ZARF_REGISTRY###/ironbank/opensource/ingress-nginx/kube-webhook-certgen"
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
        cleanupProxy:
          image:
            repository: "###ZARF_REGISTRY###/ironbank/big-bang/base"
          resources:
            limits:
              cpu: "50m"
              memory: "50Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
      resources:
        limits:
          cpu: "200m"
          memory: "512Mi"
        requests:
          cpu: "100m"
          memory: "256Mi"
      image:
        repository: "###ZARF_REGISTRY###/ironbank/opensource/prometheus-operator/prometheus-operator"
      prometheusConfigReloader:
        image:
          repository: "###ZARF_REGISTRY###/ironbank/opensource/prometheus-operator/prometheus-config-reloader"
        resources:
          requests:
            cpu: "50m"
            memory: "50Mi"
          limits:
            cpu: "100m"
            memory: "50Mi"
      thanosImage:
        repository: "###ZARF_REGISTRY###/ironbank/opensource/thanos/thanos"
      kubectlImage:
        repository: "###ZARF_REGISTRY###/ironbank/opensource/kubernetes-1.20/kubectl-1.20"
    prometheus:
      prometheusSpec:
        image:
          repository: "###ZARF_REGISTRY###/ironbank/opensource/prometheus/prometheus"
        resources:
          limits:
            cpu: "300m"
            memory: "5Gi"
          requests:
            cpu: "50m"
            memory: "2Gi"

twistlock:
  enabled: true
  git:
    repo: http://zarf-gitea-http.zarf.svc.cluster.local:3000/zarf-git-user/mirror__repo1.dso.mil__platform-one__big-bang__apps__security-tools__twistlock.git
  values:
    console:
      image:
        repository: "###ZARF_REGISTRY###/ironbank/twistlock/console/console"
    resources:
      limits:
        memory: "1Gi"
        cpu: "250m"
      requests:
        memory: "256Mi"
        cpu: "50m"
    bbtests:
      scripts:
        image: "###ZARF_REGISTRY###/ironbank/stedolan/jq:1.6"
