apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwix-serve
  namespace: kiwix
  labels:
    app: kiwix-serve
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kiwix-serve
  template:
    metadata:
      labels:
        app: kiwix-serve
    spec:
      containers:
        - name: kiwix-serve
          image: "ghcr.io/kiwix/kiwix-serve:3.5.0-2"
          command:
            [
              "sh",
              "-c",
              "ls -la /kiwix-data/data && kiwix-serve -v /kiwix-data/data/*.zim",
            ]
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          volumeMounts:
            - name: data
              mountPath: /kiwix-data
          readinessProbe:
            httpGet:
              path: /
              port: 80
      volumes:
        - name: data
          image:
            reference: kiwix-data:local
            pullPolicy: "Always"
