apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "docker-registry.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "docker-registry.name" . }}
      release: {{ .Release.Name }}
  {{ if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{ end }}
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: {{ template "docker-registry.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 8 }}
        {{- end }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
{{- if .Values.mtls.enabled }}
{{- $tlsSecret := (lookup "v1" "Secret" .Release.Namespace "zarf-registry-server-tls") }}
{{- if $tlsSecret }}
        checksum/tls-secret: {{ $tlsSecret.data | toJson | sha256sum }}
{{- end }}
{{- end }}
    spec:
      serviceAccountName: {{ include "docker-registry.serviceAccountName" . }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      priorityClassName: system-node-critical
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        seccompProfile:
          type: "RuntimeDefault"
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ include "registry.image.repository" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          command:
          - /bin/registry
          - serve
          - /etc/docker/registry/config.yml
          ports:
            - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: {{ if .Values.mtls.enabled }}HTTPS{{ else }}HTTP{{ end }}
          readinessProbe:
            httpGet:
              path: /
              port: 5000
              scheme: {{ if .Values.mtls.enabled }}HTTPS{{ else }}HTTP{{ end }}
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            capabilities:
              drop: ["ALL"]
          resources:
{{ toYaml .Values.resources | indent 12 }}
          env:
            - name: REGISTRY_AUTH
              value: "htpasswd"
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: "Registry Realm"
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: "/etc/docker/registry/htpasswd"
            - name: OTEL_TRACES_EXPORTER
              value: {{ .Values.opentelemetry.exporter | default "otlp" }}
{{- if .Values.persistence.enabled }}
            - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
              value: "/var/lib/registry"
{{- end }}
{{- if .Values.persistence.deleteEnabled }}
            - name: REGISTRY_STORAGE_DELETE_ENABLED
              value: "true"
{{- end }}
{{- with .Values.extraEnvVars }}
{{ toYaml .  | indent 12 }}
{{- end }}
          volumeMounts:
{{- if .Values.mtls.enabled }}
            - name: server-certs
              mountPath: /certs/server
              readOnly: true
{{- end }}
            - name: data
              mountPath: /var/lib/registry/
            - name: config
              mountPath: "/etc/docker/registry"
{{- if .Values.caBundle }}
            - mountPath: /etc/ssl/certs/ca-certificates.crt
              name: {{ template "docker-registry.fullname" . }}-ca-bundle
              subPath: ca-certificates.crt
              readOnly: true
{{- end }}
{{- if .Values.affinity.enabled }}
      affinity:
{{- if .Values.affinity.custom }}
{{ toYaml .Values.affinity.custom | indent 8 }}
{{- else }}
{{- if (eq "ReadWriteMany" .Values.persistence.accessMode) }}
        podAntiAffinity:
{{- else }}
        podAffinity:
{{- end }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "docker-registry.name" . }}
                topologyKey: kubernetes.io/hostname
{{- end }}
{{- end }}
{{- if .Values.tolerations}}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
      volumes:
{{- if .Values.mtls.enabled }}
        - name: server-certs
          secret:
            secretName: zarf-registry-server-tls
{{- end }}
        - name: config
          secret:
            secretName: {{ template "docker-registry.fullname" . }}-secret
            items:
            - key: configData
              path: config.yml
            - key: htpasswd
              path: htpasswd
{{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "docker-registry.fullname" . }}{{- end }}
{{- else }}
        - name: data
          emptyDir:
            sizeLimit: {{ .Values.persistence.size }}
{{- end }}
{{- if .Values.caBundle }}
        - name: {{ template "docker-registry.fullname" . }}-ca-bundle
          configMap:
            name: {{ template "docker-registry.fullname" . }}-ca-bundle
{{- end }}
