apiVersion: v1
kind: Secret
metadata:
  name: {{ template "docker-registry.fullname" . }}-secret
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    app: {{ template "docker-registry.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
stringData:
  configData: {{ include "docker-registry.configData" . | quote }}
data:
  validateSecretValue: {{ required "A valid secrets.configData.http.secret value is required in the values.yaml" .Values.secrets.configData.http.secret | b64enc | quote }}
  htpasswd: {{ .Values.secrets.htpasswd | b64enc }}
