name: Check for go mod changes
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate-go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Test go mod
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum
