name: docs
on:
  pull_request:
    paths:
      - '**.md'
      - '**.jpg'
      - '**.png'
      - '**.gif'
      - '**.svg'
      - 'adr/**'
      - 'docs/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "Not required, non-code changes only." '      
