name: Validate Docs and Schema
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate-docs-and-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Docs and schemas
        run: "make test-docs-and-schema"

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
