name: Validate Docs and Schema
on:
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  validate-docs-and-schema:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Setup golang
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod

      - name: Docs and schemas
        run: "make test-docs-and-schema"

      - name: Instruct user to fix
        if: failure()
        run: echo "Please run 'make docs-and-schema' at the root of the repo and commit the changes to your pull request"
