name: Test Web UI
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-ui-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Have to run early for now since UI tests are a little brittle around cluster state
      - name: Setup K3d
        uses: ./.github/actions/k3d

      - name: Setup golang
        uses: ./.github/actions/golang

      - name: Setup NodeJS
        uses: ./.github/actions/node

      - name: Build binary and zarf packages
        uses: ./.github/actions/packages

      - name: Cache browsers
        uses: actions/cache@v3
        with:
          path: "~/.cache/ms-playwright/"
          key: ${{ runner.os }}-browsers

      - name: Ensure playright is installed
        run: npx playwright install

      - name: Run UI tests
        run: >
          NODE_PATH=$(pwd)/src/ui/node_modules
          npm --prefix src/ui run test:pre-init &&
          NODE_PATH=$(pwd)/src/ui/node_modules
          npm --prefix src/ui run test:init &&
          NODE_PATH=$(pwd)/src/ui/node_modules
          npm --prefix src/ui run test:post-init

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs

      - name: Save playright logs
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
