name: test-ui
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Dependency: Install Golang"
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.x

      - name: "Dependency: Install K3d"
        run: "curl -s https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash"

      - name: "Dependency: K3d cluster init"
        run: k3d cluster delete && k3d cluster create

      - name: "Checkout Repo"
        uses: actions/checkout@v3

      - name: "Setup caching"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache browsers
        uses: actions/cache@v3
        with:
          path: '~/Library/Caches/ms-playwright/'
          key: ${{ runner.os }}-browsers            

      - name: "Build CLI"
        run: make build-cli-linux-amd ARCH=amd64

      - name: "Zarf Agent: Login to Docker Hub"
        uses: docker/login-action@v2
        with:
          username: zarfdev
          password: ${{ secrets.ZARF_DEV_DOCKERHUB }}

      - name: "Zarf Agent: Build and Publish the Image"
        run: |
          cp build/zarf build/zarf-linux-amd64
          docker buildx build --push --platform linux/amd64 --tag zarfdev/agent:$GITHUB_SHA .

      - name: "Make Packages"
        run: make init-package build-examples ARCH=amd64 AGENT_IMAGE=zarfdev/agent:$GITHUB_SHA

      - name: "Dependency: Playwright Browsers"
        run: npx playwright install

      - name: "Run Tests"
        # NOTE: This test run will create its own K3d cluster. A single cluster will be used throughout the test run.
        run: npm test

      - name: "Save test debug logs"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: debug-log
          path: /tmp/zarf-*.log

      - name: "Save ui test reports"
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

      - name: "Cleanup"
        run: |
          make destroy
