name: Test Import
on:
  pull_request:

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: import-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-import:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod

      - name: Run test Go program that imports Zarf
        run: |
          cd $(mktemp -d)
          echo "$GO_MAIN" > main.go
          go mod init github.com/zarf-dev/test-import
          go mod edit -replace github.com/zarf-dev/zarf=github.com/${{ github.event.pull_request.head.repo.full_name }}@${COMMIT_SHA:0:12}
          go mod tidy
          cat go.mod | grep -q ${COMMIT_SHA:0:12}
          go run main.go
        env:
          COMMIT_SHA: ${{ github.event.pull_request.head.sha }}
          GO_MAIN: |
            package main

            import (
            	"fmt"

            	"github.com/zarf-dev/zarf/src/api/v1alpha1"
            	"github.com/zarf-dev/zarf/src/pkg/packager"
            )

            func main() {
            	fmt.Println(packager.PullOptions{})
            	fmt.Println(v1alpha1.ZarfComponent{})
            }
