name: Test Windows Binary
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      # - name: Optimize caching
      #   run: echo C:\Program Files\Git\usr\bin>>"%GITHUB_PATH%"
      #   shell: cmd

      - name: Setup golang
        uses: ./.github/actions/golang

      # - name: set go cache paths
      #   id: go-cache-paths
      #   run: |
      #     Write-Output "::set-output name=go-build::$(go env GOCACHE)"
      #     Write-Output "::set-output name=go-mod::$(go env GOMODCACHE)"
      #   shell: pwsh

      # - name: Cache Go modules
      #   id: cache-go-mod
      #   uses: actions/cache@v4
      #   with:
      #     path: |
      #       ${{ steps.go-cache-paths.outputs.go-build }}
      #       ${{ steps.go-cache-paths.outputs.go-mod }}
      #     key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      #     restore-keys: |
      #       ${{ runner.os }}-go-

      - name: Run Windows unit tests
        run: make test-unit
        shell: pwsh

      - name: Build Windows binary and zarf packages
        uses: ./.github/actions/packages
        with:
          init-package: "false"
          os: windows
          shell: pwsh

      # TODO: (@WSTARR) Builds an init package manually off of the v0.30.1
      # release since Windows in GitHub cannot natively build linux containers
      # and the tests this workflow run do not use the agent at all!
      - name: Build init-package
        run: |
          make release-init-package ARCH=amd64 AGENT_IMAGE_TAG=v0.30.1

      - name: Run windows E2E tests
        run: make test-e2e-without-cluster
        shell: pwsh
