name: Test Windows Binary
on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"
  merge_group:
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - "CODEOWNERS"

permissions:
  contents: read

# Abort prior jobs in the same workflow / PR
concurrency:
  group: e2e-windows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-unit:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup golang
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod

      - name: Run Windows unit tests
        run: make test-unit
        shell: pwsh

  test-e2e-without-cluster:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4.2.1

      - name: Setup golang
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: go.mod

      - name: Build Windows binary and zarf packages
        uses: ./.github/actions/packages
        with:
          init-package: "false"
          os: windows
          shell: pwsh

      # TODO: (@WSTARR) Builds an init package manually off of the v0.30.1
      # release since Windows in GitHub cannot natively build linux containers
      # and the tests this workflow run do not use the agent at all!
      - name: Build init-package
        run: |
          make release-init-package ARCH=amd64 AGENT_IMAGE_TAG=v0.30.1

      - name: Run windows E2E tests
        run: make test-e2e-without-cluster
        shell: pwsh
